import { createSettingsSchema } from "./settings.schema";
import type { SettingsSchema } from "./settings.types";

const rawSettingsSchema: SettingsSchema = {
  categories: [
    "Appearance",
    "CommandCenter",
    "Offline",
    "Tags",
    "FileManager",
    "Performance",
    "Advanced",
    "Support & Community",
    "Danger Zone",
  ],
  items: [
    {
      id: "theme",
      label: "Change Theme",
      description: "Choose a full visual identity for the app.",
      type: "theme",
      category: "Appearance",
      defaultValue: "classic",
      options: [
        { label: "Classic", value: "classic" },
        { label: "Midnight", value: "midnight" },
        { label: "Forest", value: "forest" },
        { label: "Sunset", value: "sunset" },
        { label: "Minimal", value: "minimal" },
        { label: "Eclipse", value: "eclipse" },
        { label: "Graphite", value: "graphite" },
      ]
    },
    {
      id: "compact_mode",
      label: "Compact Mode",
      description: "Reduces list density and spacing across interface rows.",
      type: "toggle",
      category: "Appearance",
      defaultValue: false,
    },
    {
      id: "animation_intensity",
      label: "Animation Intensity",
      description: "Controls motion intensity for transitions and interactions.",
      type: "slider",
      category: "Appearance",
      defaultValue: 60,
      min: 0,
      max: 100,
      step: 5,
    },
    {
      id: "show_dashboard_quote",
      label: "Show Daily Quote",
      description: "Display a motivational quote on the dashboard.",
      type: "toggle",
      category: "Appearance",
      defaultValue: true,
    },
    {
      id: "enable_haptics",
      label: "Use Haptic Feedback",
      description: "Enable brief vibrations on supported devices during interactions.",
      type: "toggle",
      category: "Appearance",
      defaultValue: false,
    },
    {
      id: "default_sort_order",
      label: "Default Course Sort",
      description: "Initial sorting sequence used for the Course Library on the Dashboard.",
      type: "select",
      category: "Appearance",
      defaultValue: "recent",
      options: [
        { label: "Recently Opened", value: "recent" },
        { label: "Alphabetical (A-Z)", value: "name" },
        { label: "Credits", value: "credits" },
      ],
    },
    {
      id: "dashboard_default_view",
      label: "Dashboard Default View",
      description: "Default visual layout for courses on the dashboard.",
      type: "select",
      category: "Appearance",
      defaultValue: "grid",
      options: [
        { label: "Grid", value: "grid" },
        { label: "List", value: "list" },
      ],
    },
    {
      id: "show_dashboard_tags",
      label: "Show Filter Tags",
      description: "Display quick-access filter tags above the course list.",
      type: "toggle",
      category: "Appearance",
      defaultValue: true,
    },
    {
      id: "disable_glass_effects",
      label: "Disable Glass Effects",
      description: "Turn off backdrop blurs and translucency for higher performance.",
      type: "toggle",
      category: "Performance",
      defaultValue: false,
    },
    {
      id: "search_debounce",
      label: "Search Debounce (ms)",
      description: "Delay before command search executes after typing.",
      type: "slider",
      category: "CommandCenter",
      defaultValue: 40,
      min: 20,
      max: 250,
      step: 5,
    },
    {
      id: "fuzzy_search_enabled",
      label: "Enable Fuzzy Search",
      description: "Allow approximate matching in command center results.",
      type: "toggle",
      category: "CommandCenter",
      defaultValue: true,
    },
    {
      id: "result_limit",
      label: "Result Limit",
      description: "Maximum number of command center results.",
      type: "select",
      category: "CommandCenter",
      defaultValue: "50",
      options: [
        { label: "20", value: "20" },
        { label: "50", value: "50" },
        { label: "100", value: "100" },
      ],
    },
    {
      id: "auto_prefetch",
      label: "Auto Prefetch",
      description: "Prefetch nearby files in folder flows for faster open times.",
      type: "toggle",
      category: "Offline",
      defaultValue: true,
    },
    {
      id: "storage_location",
      label: "Storage Location",
      description: "Where offline files are stored on your device.",
      type: "info",
      category: "Offline",
    },
    {
      id: "storage_limit_mb",
      label: "Storage Limit (MB)",
      description: "Maximum offline storage budget used by cache operations.",
      type: "slider",
      category: "Offline",
      defaultValue: 500,
      min: 100,
      max: 2000,
      step: 50,
    },
    {
      id: "default_view_mode",
      label: "Default View Mode",
      description: "Default file manager view mode.",
      type: "select",
      category: "FileManager",
      defaultValue: "grid",
      options: [
        { label: "Grid", value: "grid" },
        { label: "List", value: "list" },
      ],
    },
    {
      id: "show_file_metadata",
      label: "Show File Metadata",
      description: "Display metadata details in file listings and previews.",
      type: "toggle",
      category: "FileManager",
      defaultValue: true,
    },
    {
      id: "tag_filter_mode_default",
      label: "Default Tag Filter Mode",
      description: "Default mode for multi-tag filtering behavior.",
      type: "select",
      category: "Tags",
      defaultValue: "OR",
      options: [
        { label: "AND", value: "AND" },
        { label: "OR", value: "OR" },
      ],
    },
    {
      id: "virtualized_lists",
      label: "Virtualized Lists",
      description: "Enable virtualized rendering for large file sets.",
      type: "toggle",
      category: "Performance",
      defaultValue: true,
      advanced: true,
      requiresRestart: true,
    },
    {
      id: "cache_warmup_on_start",
      label: "Cache Warmup on Start",
      description: "Warm selected caches during app startup.",
      type: "toggle",
      category: "Performance",
      defaultValue: false,
      advanced: true,
    },
    {
      id: "debug_command_scoring",
      label: "Debug Command Scoring",
      description: "Expose command ranking signals for debugging.",
      type: "toggle",
      category: "Advanced",
      defaultValue: false,
      advanced: true,
    },
    {
      id: "github_source",
      label: "View Source Code",
      description: "Visit the GitHub repository for Studytrix.",
      buttonLabel: "Open",
      type: "action",
      category: "Support & Community",
    },
    {
      id: "give_feedback",
      label: "Give Feedback",
      description: "Share your thoughts and suggestions.",
      buttonLabel: "Go",
      type: "action",
      category: "Support & Community",
    },
    {
      id: "report_issue",
      label: "Report an Issue",
      description: "Found a bug? Let us know so we can fix it.",
      buttonLabel: "Report",
      type: "action",
      category: "Support & Community",
    },
    {
      id: "suggest_feature",
      label: "Suggest a Feature",
      description: "Have an idea? We'd love to hear it.",
      buttonLabel: "Suggest",
      type: "action",
      category: "Support & Community",
    },
    {
      id: "contact_support",
      label: "Contact Support",
      description: "Reach out to us directly via email.",
      buttonLabel: "Contact",
      type: "action",
      category: "Support & Community",
    },
    {
      id: "clear_offline_storage",
      label: "Clear Offline Storage",
      description: "Remove all offline files and local offline search index.",
      type: "danger",
      category: "Danger Zone",
    },
    {
      id: "reset_all_settings",
      label: "Reset All Settings",
      description: "Restore every setting to its default value.",
      type: "danger",
      category: "Danger Zone",
    },
  ],
};

export const SETTINGS_SCHEMA = createSettingsSchema(rawSettingsSchema);
