import { createSettingsSchema } from "./settings.schema";
import type { SettingsSchema } from "./settings.types";

const rawSettingsSchema: SettingsSchema = {
  categories: [
    "Profile",
    "Appearance",
    "Dashboard",
    "Command Center",
    "Intelligence",
    "Repositories",
    "Offline & Storage",
    "Sharing",
    "Performance",
    "Advanced",
  ],
  items: [
    {
      id: "userProfile",
      label: "Profile Details",
      description: "Personal details used for personalized greetings.",
      type: "info",
      category: "Profile",
      defaultValue: {
        name: "",
        email: "",
      },
    },
    {
      id: "greetingPreferences",
      label: "Dashboard Greeting",
      description: "Control greeting visibility, weather context, and tone.",
      type: "info",
      category: "Profile",
      defaultValue: {
        enabled: true,
        includeWeather: true,
        useName: true,
        greetingTheme: "study",
      },
    },
    {
      id: "theme",
      label: "Theme",
      description: "Choose your preferred visual style.",
      type: "theme",
      category: "Appearance",
      defaultValue: "classic",
      options: [
        { label: "Classic", value: "classic" },
        { label: "Midnight", value: "midnight" },
        { label: "Forest", value: "forest" },
        { label: "Sunset", value: "sunset" },
        { label: "Minimal", value: "minimal" },
        { label: "Eclipse", value: "eclipse" },
        { label: "Graphite", value: "graphite" },
      ],
    },
    {
      id: "compact_mode",
      label: "Compact Layout",
      description: "Reduce spacing density across lists and setting rows.",
      type: "toggle",
      category: "Appearance",
      defaultValue: false,
    },
    {
      id: "animation_intensity",
      label: "Animation Intensity",
      description: "Adjust motion intensity for transitions and interactions.",
      type: "slider",
      category: "Appearance",
      defaultValue: 60,
      min: 0,
      max: 100,
      step: 5,
    },
    {
      id: "enable_haptics",
      label: "Haptic Feedback",
      description: "Vibrate briefly on supported devices for key actions.",
      type: "toggle",
      category: "Appearance",
      defaultValue: false,
    },
    {
      id: "default_sort_order",
      label: "Default Course Sort",
      description: "Choose the initial sort order for course and repository cards.",
      type: "select",
      category: "Dashboard",
      defaultValue: "recent",
      options: [
        { label: "Recently Opened", value: "recent" },
        { label: "Alphabetical (A-Z)", value: "name" },
        { label: "Credits", value: "credits" },
      ],
    },
    {
      id: "dashboard_default_view",
      label: "Default Dashboard View",
      description: "Select the default card layout on repository screens.",
      type: "select",
      category: "Dashboard",
      defaultValue: "grid",
      options: [
        { label: "Grid", value: "grid" },
        { label: "List", value: "list" },
      ],
    },
    {
      id: "show_dashboard_tags",
      label: "Show Tag Filters",
      description: "Display quick tag filters above repository lists.",
      type: "toggle",
      category: "Dashboard",
      defaultValue: true,
    },
    {
      id: "tag_filter_mode_default",
      label: "Default Tag Match Mode",
      description: "Pick whether tag filters match Any or All selected tags by default.",
      type: "select",
      category: "Dashboard",
      defaultValue: "OR",
      options: [
        { label: "Any (OR)", value: "OR" },
        { label: "All (AND)", value: "AND" },
      ],
    },
    {
      id: "show_header_motivation",
      label: "Show Header Motivation",
      description: "Show the dashboard motivation line in the top header.",
      type: "toggle",
      category: "Dashboard",
      defaultValue: true,
    },
    {
      id: "show_version_update_banner",
      label: "Show Version Update Banner",
      description: "Display release update highlights after app upgrades.",
      type: "toggle",
      category: "Dashboard",
      defaultValue: true,
    },
    {
      id: "search_debounce",
      label: "Search Debounce (ms)",
      description: "Delay before command search runs after typing.",
      type: "slider",
      category: "Command Center",
      defaultValue: 40,
      min: 20,
      max: 250,
      step: 5,
    },
    {
      id: "fuzzy_search_enabled",
      label: "Enable Fuzzy Search",
      description: "Allow approximate keyword matches in command results.",
      type: "toggle",
      category: "Command Center",
      defaultValue: true,
    },
    {
      id: "result_limit",
      label: "Result Limit",
      description: "Maximum number of command results returned per query.",
      type: "select",
      category: "Command Center",
      defaultValue: "50",
      options: [
        { label: "20", value: "20" },
        { label: "50", value: "50" },
        { label: "100", value: "100" },
      ],
    },
    {
      id: "semantic_search_enabled",
      label: "Smart Search",
      description: "Uses on-device AI to understand intent. ~34MB one-time download.",
      type: "toggle",
      category: "Intelligence",
      defaultValue: false,
    },
    {
      id: "semantic_search_show_in_commandcenter",
      label: "Show in Command Center",
      description: "Show the Smart Search toggle row below the search input.",
      type: "toggle",
      category: "Intelligence",
      defaultValue: true,
    },
    {
      id: "semantic_search_index_status",
      label: "Index Status",
      description: "Review indexed file counts and index freshness.",
      type: "info",
      category: "Intelligence",
    },
    {
      id: "semantic_search_rebuild_index",
      label: "Rebuild Index",
      description: "Clear and rebuild the Smart Search index from scratch.",
      type: "action",
      category: "Intelligence",
      buttonLabel: "Rebuild",
    },
    {
      id: "semantic_search_clear_index",
      label: "Clear Index",
      description: "Delete the current search index. Smart Search stops until rebuilt.",
      type: "danger",
      category: "Intelligence",
    },
    {
      id: "semantic_search_model_status",
      label: "Model Status",
      description: "Current embedding model availability on this device.",
      type: "info",
      category: "Intelligence",
    },
    {
      id: "semantic_search_remove_model",
      label: "Remove Model",
      description: "Delete the downloaded AI model to free ~34MB of storage.",
      type: "danger",
      category: "Intelligence",
    },
    {
      id: "semantic_search_learn_more",
      label: "Learn how Smart Search works",
      description: "Open the Smart Search architecture overview.",
      type: "action",
      category: "Intelligence",
      buttonLabel: "Open",
    },
    {
      id: "semantic_search_experimental_notice",
      label: "Smart Search is experimental",
      description: "Results may be inaccurate.",
      type: "info",
      category: "Intelligence",
    },
    {
      id: "personal_repository_visible",
      label: "Show Personal Repository",
      description: "Show or hide the Personal Repository tab in repository screens.",
      type: "toggle",
      category: "Repositories",
      defaultValue: true,
    },
    {
      id: "personal_repository",
      label: "Open Personal Repository",
      description: "Jump directly to your Personal Repository workspace.",
      buttonLabel: "Open",
      type: "action",
      category: "Repositories",
    },
    {
      id: "personal_repository_clear_all",
      label: "Delete All Personal Folders",
      description: "Remove every folder saved in Personal Repository.",
      type: "danger",
      category: "Repositories",
    },
    {
      id: "default_view_mode",
      label: "Default File Manager View",
      description: "Choose the default layout for folder file listings.",
      type: "select",
      category: "Repositories",
      defaultValue: "grid",
      options: [
        { label: "Grid", value: "grid" },
        { label: "List", value: "list" },
      ],
    },
    {
      id: "show_file_metadata",
      label: "Show File Metadata",
      description: "Display metadata in file listings and previews.",
      type: "toggle",
      category: "Repositories",
      defaultValue: true,
    },
    {
      id: "storage_location",
      label: "Storage Location",
      description: "Current location used for local offline files.",
      type: "info",
      category: "Offline & Storage",
    },
    {
      id: "storage_limit_mb",
      label: "Storage Limit (MB)",
      description: "Maximum local storage budget for offline data.",
      type: "slider",
      category: "Offline & Storage",
      defaultValue: 500,
      min: 100,
      max: 2000,
      step: 50,
    },
    {
      id: "auto_prefetch",
      label: "Auto Prefetch",
      description: "Preload nearby files in folder flows for faster opening.",
      type: "toggle",
      category: "Offline & Storage",
      defaultValue: true,
    },
    {
      id: "show_connectivity_banner",
      label: "Show Connectivity Banner",
      description: "Show online/offline state updates at the top of pages.",
      type: "toggle",
      category: "Offline & Storage",
      defaultValue: true,
    },
    {
      id: "clear_offline_storage",
      label: "Clear Offline Storage",
      description: "Remove all offline files and local offline search data.",
      type: "danger",
      category: "Offline & Storage",
    },
    {
      id: "page_share_preference",
      label: "Page Share Preference",
      description: "Choose whether sharing prioritizes native share or copied links.",
      type: "select",
      category: "Sharing",
      defaultValue: "native_share",
      options: [
        { label: "Native Share First", value: "native_share" },
        { label: "Copy Link First", value: "copy_link" },
      ],
    },
    {
      id: "share_include_academic_context",
      label: "Include Academic Context in Shared Links",
      description: "Attach department and semester context when sharing home links.",
      type: "toggle",
      category: "Sharing",
      defaultValue: true,
    },
    {
      id: "disable_glass_effects",
      label: "Disable Glass Effects",
      description: "Turn off blur/translucency effects for steadier rendering.",
      type: "toggle",
      category: "Performance",
      defaultValue: false,
    },
    {
      id: "virtualized_lists",
      label: "Virtualized Lists",
      description: "Use virtualization for large file/result lists.",
      type: "toggle",
      category: "Performance",
      defaultValue: true,
      advanced: true,
      requiresRestart: true,
    },
    {
      id: "cache_warmup_on_start",
      label: "Warm Caches on Startup",
      description: "Preload key caches during app startup.",
      type: "toggle",
      category: "Performance",
      defaultValue: false,
      advanced: true,
    },
    {
      id: "debug_command_scoring",
      label: "Debug Command Scoring",
      description: "Expose command ranking signals for diagnostics.",
      type: "toggle",
      category: "Advanced",
      defaultValue: false,
      advanced: true,
    },
    {
      id: "experimental_features_opt_in",
      label: "Enable Experimental Features",
      description: "Enable opt-in experimental capabilities.",
      type: "toggle",
      category: "Advanced",
      defaultValue: false,
      advanced: true,
    },
    {
      id: "semantic_search_notice_dismissed",
      label: "Smart Search Notice Dismissed",
      description: "Internal flag for one-time Smart Search notice dismissal.",
      type: "toggle",
      category: "Advanced",
      defaultValue: false,
      advanced: true,
    },
  ],
};

export const SETTINGS_SCHEMA = createSettingsSchema(rawSettingsSchema);
