import { createSettingsSchema } from "./settings.schema";
import type { SettingsSchema } from "./settings.types";

const rawSettingsSchema: SettingsSchema = {
  categories: [
    "Profile",
    "Appearance",
    "Greeting",
    "CommandCenter",
    "Intelligence",
    "Offline",
    "Tags",
    "FileManager",
    "Sharing",
    "Performance",
    "Advanced",
    "Support & Community",
    "Danger Zone",
  ],
  items: [
    {
      id: "userProfile",
      label: "Profile",
      description: "Personal details used for greeting personalization.",
      type: "info",
      category: "Profile",
      defaultValue: {
        name: "",
        email: "",
      },
    },
    {
      id: "theme",
      label: "Change Theme",
      description: "Choose a full visual identity for the app.",
      type: "theme",
      category: "Appearance",
      defaultValue: "classic",
      options: [
        { label: "Classic", value: "classic" },
        { label: "Midnight", value: "midnight" },
        { label: "Forest", value: "forest" },
        { label: "Sunset", value: "sunset" },
        { label: "Minimal", value: "minimal" },
        { label: "Eclipse", value: "eclipse" },
        { label: "Graphite", value: "graphite" },
      ]
    },
    {
      id: "compact_mode",
      label: "Compact Mode",
      description: "Reduces list density and spacing across interface rows.",
      type: "toggle",
      category: "Appearance",
      defaultValue: false,
    },
    {
      id: "animation_intensity",
      label: "Animation Intensity",
      description: "Controls motion intensity for transitions and interactions.",
      type: "slider",
      category: "Appearance",
      defaultValue: 60,
      min: 0,
      max: 100,
      step: 5,
    },
    {
      id: "greetingPreferences",
      label: "Greeting Preferences",
      description: "Customize dashboard greeting behavior and style.",
      type: "info",
      category: "Greeting",
      defaultValue: {
        enabled: true,
        includeWeather: true,
        useName: true,
        greetingTheme: "study",
      },
    },
    {
      id: "enable_haptics",
      label: "Use Haptic Feedback",
      description: "Enable brief vibrations on supported devices during interactions.",
      type: "toggle",
      category: "Appearance",
      defaultValue: false,
    },
    {
      id: "default_sort_order",
      label: "Default Course Sort",
      description: "Initial sorting sequence used for the Course Library on the Dashboard.",
      type: "select",
      category: "Appearance",
      defaultValue: "recent",
      options: [
        { label: "Recently Opened", value: "recent" },
        { label: "Alphabetical (A-Z)", value: "name" },
        { label: "Credits", value: "credits" },
      ],
    },
    {
      id: "dashboard_default_view",
      label: "Dashboard Default View",
      description: "Default visual layout for courses on the dashboard.",
      type: "select",
      category: "Appearance",
      defaultValue: "grid",
      options: [
        { label: "Grid", value: "grid" },
        { label: "List", value: "list" },
      ],
    },
    {
      id: "show_dashboard_tags",
      label: "Show Filter Tags",
      description: "Display quick-access filter tags above the course list.",
      type: "toggle",
      category: "Appearance",
      defaultValue: true,
    },
    {
      id: "show_header_motivation",
      label: "Show Header Motivation",
      description: "Display the dashboard header motivation line on the home page.",
      type: "toggle",
      category: "Appearance",
      defaultValue: true,
    },
    {
      id: "show_version_update_banner",
      label: "Show Version Update Banner",
      description: "Display the changelog update banner after new app versions.",
      type: "toggle",
      category: "Appearance",
      defaultValue: true,
    },
    {
      id: "disable_glass_effects",
      label: "Disable Glass Effects",
      description: "Turn off backdrop blurs and translucency for higher performance.",
      type: "toggle",
      category: "Performance",
      defaultValue: false,
    },
    {
      id: "search_debounce",
      label: "Search Debounce (ms)",
      description: "Delay before command search executes after typing.",
      type: "slider",
      category: "CommandCenter",
      defaultValue: 40,
      min: 20,
      max: 250,
      step: 5,
    },
    {
      id: "fuzzy_search_enabled",
      label: "Enable Fuzzy Search",
      description: "Allow approximate matching in command center results.",
      type: "toggle",
      category: "CommandCenter",
      defaultValue: true,
    },
    {
      id: "result_limit",
      label: "Result Limit",
      description: "Maximum number of command center results.",
      type: "select",
      category: "CommandCenter",
      defaultValue: "50",
      options: [
        { label: "20", value: "20" },
        { label: "50", value: "50" },
        { label: "100", value: "100" },
      ],
    },
    {
      id: "intelligence_smart_search_enabled",
      label: "Smart Search",
      description: "Use semantic search to understand intent beyond exact keyword matches.",
      type: "toggle",
      category: "Intelligence",
      defaultValue: false,
    },
    {
      id: "intelligence_ocr_enabled",
      label: "OCR for Handwritten Notes",
      description: "Attempts OCR on image files and scanned PDFs using on-device processing.",
      type: "toggle",
      category: "Intelligence",
      defaultValue: false,
    },
    {
      id: "intelligence_model_mode",
      label: "Model Selection Mode",
      description: "Auto picks a model by device profile. Manual lets you choose one explicitly.",
      type: "select",
      category: "Intelligence",
      defaultValue: "auto",
      options: [
        { label: "Auto", value: "auto" },
        { label: "Manual", value: "manual" },
      ],
    },
    {
      id: "intelligence_model_id",
      label: "Embedding Model",
      description: "Sentence-transformer model used for semantic ranking in CommandCenter.",
      type: "select",
      category: "Intelligence",
      defaultValue: "Xenova/all-MiniLM-L6-v2",
      options: [
        { label: "all-MiniLM-L6-v2", value: "Xenova/all-MiniLM-L6-v2" },
        { label: "bge-small-en-v1.5", value: "Xenova/bge-small-en-v1.5" },
      ],
    },
    {
      id: "intelligence_cleanup_model_id",
      label: "Cleanup Engine",
      description: "Model used to clean OCR text before copy. Stored locally on this device.",
      type: "select",
      category: "Intelligence",
      defaultValue: "Xenova/t5-tiny",
      options: [
        { label: "Lite (T5 Tiny, ~15MB)", value: "Xenova/t5-tiny" },
        { label: "Balanced (T5 Small, ~40MB)", value: "Xenova/t5-small" },
        { label: "Pro (BART Base, ~100MB)", value: "Xenova/bart-base-cnn" },
      ],
    },
    {
      id: "intelligence_semantic_weight",
      label: "Semantic Weight",
      description: "Blending strength for semantic ranking over keyword score (0-100).",
      type: "slider",
      category: "Intelligence",
      defaultValue: 60,
      min: 0,
      max: 100,
      step: 1,
      advanced: true,
    },
    {
      id: "intelligence_duplicate_detection_enabled",
      label: "Duplicate Detection",
      description: "Flags files that appear to be duplicates. Runs quietly in the background.",
      type: "toggle",
      category: "Intelligence",
      defaultValue: false,
    },
    {
      id: "intelligence_clear_index",
      label: "Clear Search Index",
      description: "Delete local semantic vectors and rebuild on the next indexing cycle.",
      type: "danger",
      category: "Intelligence",
    },
    {
      id: "intelligence_clear_model_cache",
      label: "Clear Model Cache",
      description: "Delete downloaded inference models. They will re-download when needed.",
      type: "danger",
      category: "Intelligence",
    },
    {
      id: "auto_prefetch",
      label: "Auto Prefetch",
      description: "Prefetch nearby files in folder flows for faster open times.",
      type: "toggle",
      category: "Offline",
      defaultValue: true,
    },
    {
      id: "storage_location",
      label: "Storage Location",
      description: "Where offline files are stored on your device.",
      type: "info",
      category: "Offline",
    },
    {
      id: "storage_limit_mb",
      label: "Storage Limit (MB)",
      description: "Maximum offline storage budget used by cache operations.",
      type: "slider",
      category: "Offline",
      defaultValue: 500,
      min: 100,
      max: 2000,
      step: 50,
    },
    {
      id: "default_view_mode",
      label: "Default View Mode",
      description: "Default file manager view mode.",
      type: "select",
      category: "FileManager",
      defaultValue: "grid",
      options: [
        { label: "Grid", value: "grid" },
        { label: "List", value: "list" },
      ],
    },
    {
      id: "show_file_metadata",
      label: "Show File Metadata",
      description: "Display metadata details in file listings and previews.",
      type: "toggle",
      category: "FileManager",
      defaultValue: true,
    },
    {
      id: "page_share_preference",
      label: "Page Share Preference",
      description: "Choose whether page share prioritizes native share or direct copy link.",
      type: "select",
      category: "Sharing",
      defaultValue: "native_share",
      options: [
        { label: "Native Share First", value: "native_share" },
        { label: "Copy Link First", value: "copy_link" },
      ],
    },
    {
      id: "share_include_academic_context",
      label: "Include Academic Context In Shared Links",
      description: "Include department and semester query params when sharing the home page.",
      type: "toggle",
      category: "Sharing",
      defaultValue: true,
    },
    {
      id: "tag_filter_mode_default",
      label: "Default Tag Filter Mode",
      description: "Default mode for multi-tag filtering behavior.",
      type: "select",
      category: "Tags",
      defaultValue: "OR",
      options: [
        { label: "AND", value: "AND" },
        { label: "OR", value: "OR" },
      ],
    },
    {
      id: "virtualized_lists",
      label: "Virtualized Lists",
      description: "Enable virtualized rendering for large file sets.",
      type: "toggle",
      category: "Performance",
      defaultValue: true,
      advanced: true,
      requiresRestart: true,
    },
    {
      id: "cache_warmup_on_start",
      label: "Cache Warmup on Start",
      description: "Warm selected caches during app startup.",
      type: "toggle",
      category: "Performance",
      defaultValue: false,
      advanced: true,
    },
    {
      id: "debug_command_scoring",
      label: "Debug Command Scoring",
      description: "Expose command ranking signals for debugging.",
      type: "toggle",
      category: "Advanced",
      defaultValue: false,
      advanced: true,
    },
    {
      id: "experimental_features_opt_in",
      label: "Enable Experimental Features",
      description: "Opt in to beta/experimental features that are tagged with pre-release version channels.",
      type: "toggle",
      category: "Advanced",
      defaultValue: false,
      advanced: true,
    },
    {
      id: "show_connectivity_banner",
      label: "Show Connectivity Banner",
      description: "Display connection state updates at the top of pages.",
      type: "toggle",
      category: "Offline",
      defaultValue: true,
    },
    {
      id: "github_source",
      label: "View Source Code",
      description: "Visit the GitHub repository for Studytrix.",
      buttonLabel: "Open",
      type: "action",
      category: "Support & Community",
    },
    {
      id: "give_feedback",
      label: "Give Feedback",
      description: "Share your thoughts and suggestions.",
      buttonLabel: "Go",
      type: "action",
      category: "Support & Community",
    },
    {
      id: "report_issue",
      label: "Report an Issue",
      description: "Found a bug? Let us know so we can fix it.",
      buttonLabel: "Report",
      type: "action",
      category: "Support & Community",
    },
    {
      id: "suggest_feature",
      label: "Suggest a Feature",
      description: "Have an idea? We'd love to hear it.",
      buttonLabel: "Suggest",
      type: "action",
      category: "Support & Community",
    },
    {
      id: "contact_support",
      label: "Contact Support",
      description: "Reach out to us directly via email.",
      buttonLabel: "Contact",
      type: "action",
      category: "Support & Community",
    },
    {
      id: "clear_offline_storage",
      label: "Clear Offline Storage",
      description: "Remove all offline files and local offline search index.",
      type: "danger",
      category: "Danger Zone",
    },
    {
      id: "reset_all_settings",
      label: "Reset All Settings",
      description: "Restore every setting to its default value.",
      type: "danger",
      category: "Danger Zone",
    },
  ],
};

export const SETTINGS_SCHEMA = createSettingsSchema(rawSettingsSchema);
