export const TAG_SEEDS: string[] = [
  "Previous Year Questions",
  "Unit Test",
  "Assignment",
  "Lab Manual",
  "Lecture Notes",
  "Reference Book",
  "Syllabus",
  "Question Bank",
  "Handwritten Notes",
  "Slides",
  "Formula Sheet",
  "Project",
  "Research Paper",
  "Cheat Sheet",
  "Summary",
  "Video Lecture",
  "Tutorial",
  "Practice Problems",
  "Model Paper",
  "Experiment Report",
  "Case Study",
  "Textbook Chapter",
  "Module Notes",
  "Workshop Material",
  "Exam Preparation",
  "Code Sample",
  "Algorithm Notes",
  "Data Sheet",
  "Reference Manual",
  "Project Report",
  "Viva Questions",
  "Source Code",
  "Implementation",
  "Algorithm Implementation",
  "Data Structures",
  "Machine Learning Code",
  "Signal Processing Code",
  "Simulation",
  "Hardware Description",
  "Database Schema",
  "Web Development",
  "Lab Program",
  "Mini Project Code",
];

